ci(storybook): fix playwright image version
Error: Executable doesn't exist at /ms-playwright/chromium-1048/chrome-linux/chrome

Looks like Playwright Test or Playwright was just updated to 1.31.2.
Please update docker image as well.
-  current: mcr.microsoft.com/playwright:v1.32.0-focal
- required: mcr.microsoft.com/playwright:v1.31.2-focal